package text

import (
	"fmt"
	"math/rand"
	"net/http"
	"time"
)

func init() {
	rand.Seed(time.Now().UnixNano())
}

var getToKnowQuestions = []string{
	"What is something you're passionate about?",
	"What's your favorite way to spend a weekend?",
	"Do you have any hidden talents?",
	"What did you want to be when you were a kid?",
	"What's one thing on your bucket list?",
	"If you could travel anywhere in the world, where would you go?",
	"What's the best meal you've ever had?",
	"Who has had the biggest impact on your life?",
	"What was your favorite subject in school?",
	"What's a book or movie that changed your perspective?",
	"If you could have dinner with any historical figure, who would it be?",
	"What's a hobby you've always wanted to pick up?",
	"What is your favorite memory from childhood?",
	"Are you a morning person or a night owl?",
	"What's a fun fact most people don't know about you?",
	"What's something that always makes you laugh?",
	"How do you like to relax after a long day?",
	"What are you most grateful for right now?",
	"If you won the lottery, what's the first thing you'd do?",
	"What's your favorite thing about your hometown?",
	"Do you prefer the mountains, the beach, or the city?",
	"What's a skill you'd love to master?",
	"What qualities do you value most in a friend?",
	"What's your go-to comfort food?",
	"What's the most adventurous thing you've ever done?",
	"If you could instantly become an expert in anything, what would it be?",
	"What song always gets you dancing?",
	"What's your favorite holiday, and why?",
	"What's the best gift you've ever received?",
	"Do you believe in luck or destiny?",
	"What's something you wish you could tell your younger self?",
	"What's your favorite way to stay active?",
	"Do you have any pets? Tell me about them!",
	"What fictional world would you love to live in?",
	"What do you look for in a role model?",
	"What's the most interesting place you've visited?",
	"What's a tradition your family has that you love?",
	"What's something you're looking forward to?",
	"If you could have any superpower, what would it be?",
	"What's a goal you're working toward right now?",
	"What's the best concert or live event you've attended?",
	"What's something you've learned about yourself recently?",
	"Are you more of an introvert or extrovert?",
	"What's your favorite thing to cook or bake?",
	"What's a language you'd love to learn?",
	"What's your favorite way to give back to the community?",
	"If you could relive any day of your life, which would it be?",
	"What's your favorite thing about your job or studies?",
	"What's a challenge you've overcome that you're proud of?",
	"If you could meet any celebrity, who would it be?",
	"What's your favorite season, and why?",
	"What's the most meaningful compliment you've ever received?",
	"What's the best advice you've ever gotten?",
	"Do you have a favorite quote or motto?",
	"What's your favorite board game or video game?",
	"What's something you're curious about right now?",
	"If you could swap lives with anyone for a day, who would it be?",
	"What's a dream you hope to achieve one day?",
	"What's your favorite way to spend time with friends?",
	"What's something you wish more people knew about you?",
	"What's the best trip you've ever been on?",
	"What's your favorite thing about yourself?",
	"What's the weirdest food you’ve ever tried?",
	"What's your guilty pleasure song?",
	"If you could time travel, where and when would you go?",
	"What’s the best compliment you’ve given someone?",
	"What’s a hobby you tried but didn’t stick with?",
	"What’s a smell that makes you nostalgic?",
	"What’s your earliest memory?",
	"What’s a dream job you’ve thought about?",
	"If you could redo one decision, what would it be?",
	"What’s your favorite snack combo?",
	"What's a movie you can quote by heart?",
	"If you had to describe yourself in three words, what would they be?",
	"What’s your favorite ice cream flavor?",
	"What's your go-to karaoke song?",
	"If you could design your dream home, what would it look like?",
	"What’s something you’ve done that you thought you never would?",
	"What's the most random skill you have?",
	"What's a country you’d love to learn more about?",
	"What’s your favorite thing to do on a rainy day?",
	"If you had to eat one meal forever, what would it be?",
	"What's the scariest thing you've ever done for fun?",
	"What's a tradition you’d like to start?",
	"If you could instantly learn a musical instrument, which one?",
	"What’s your favorite kind of weather?",
	"What’s a city you could see yourself living in?",
	"What’s your go-to drink order?",
	"What's the best piece of technology you own?",
	"What’s your comfort TV show or movie?",
	"If you could change one thing about the world, what would it be?",
	"What’s the most spontaneous thing you’ve done?",
	"What's your favorite scent?",
	"Do you like surprises or prefer knowing everything ahead?",
	"What's the longest trip you've ever taken?",
	"If you could master any sport, what would it be?",
	"What's a fashion trend you secretly like?",
	"What’s your favorite dessert?",
	"If you had a theme song, what would it be?",
	"What's something you’d like to do more often?",
	"What's your favorite animal and why?",
	"If you had a personal assistant, what would they help with first?",
	"What's a moment that made you feel proud recently?",
	"What's a superstition you believe in, even just a little?",
	"If you could live in any era, which one would you pick?",
	"What’s the strangest dream you remember?",
	"What’s a kind gesture you’ll never forget?",
	"What’s something that instantly cheers you up?",
	"What’s a fictional character you relate to?",
	"What’s the last thing that made you cry?",
	"What’s something you could talk about for hours?",
	"What’s a skill you think everyone should have?",
	"What’s your favorite app on your phone?",
	"If you had to pick one season to live in forever, which would it be?",
	"What's the last show you binge-watched?",
	"If you could remove one common annoyance from life, what would it be?",
	"What’s a tradition you’d like to invent?",
	"If you could teleport anywhere right now, where would you go?",
	"What's your favorite public place to relax in?",
	"If you could adopt any animal in the world, what would it be?",
	"What’s the funniest misunderstanding you’ve had?",
	"If you could redo one day in your life, which one would it be?",
	"What's a little thing that makes life better?",
	"What’s your ideal weekend trip?",
	"What’s your go-to comfort activity?",
	"If you could freeze one memory forever, what would it be?",
	"What’s the best meal to share with someone?",
	"If you could learn any dance style instantly, what would you pick?",
	"What’s your idea of a perfect lazy day?",
	"If you could bring back any discontinued snack, what would it be?",
	"What’s the nicest thing someone’s done for you this year?",
	"What’s your dream type of vacation?",
	"If you had to give a TED talk, what would it be about?",
	"What’s your favorite street food?",
	"What’s a random fact you find fascinating?",
	"What’s a small luxury you enjoy?",
	"If you could spend a week learning from an expert, who would it be?",
	"What’s your favorite local restaurant?",
	"What’s a song lyric that’s stuck with you?",
	"If you had a secret hideout, what would it look like?",
	"What's your favorite smell from nature?",
	"If you could plant any tree and watch it grow instantly, what would it be?",
	"What's your favorite small town or village?",
	"What’s the most scenic place you’ve been?",
	"What’s your go-to thing to do when you can’t sleep?",
	"If you could switch lives with a fictional character, who would it be?",
	"What’s your favorite childhood cartoon?",
	"What's a place you’d love to explore at night?",
	"What’s a movie you’ve watched more than five times?",
	"If you could build anything in your backyard, what would it be?",
	"What’s your ideal way to watch the sunset?",
	"What’s your ideal way to watch the sunrise?",
	"If you could take a train anywhere, where would you go?",
	"What’s the coziest thing you own?",
	"If you could write a book, what would it be about?",
	"What’s your favorite type of bread?",
	"If you could turn any hobby into a career, which one?",
	"What’s the best outdoor activity?",
	"What's your favorite flower?",
	"If you had to choose between space or ocean exploration, which one?",
	"What’s the most peaceful place you’ve been to?",
	"If you could own a shop, what would it sell?",
	"What's the most thoughtful gift you've given?",
	"If you could create a festival, what would it celebrate?",
	"What’s the most fun thing you’ve done in the past month?",
	"If you could spend a day in nature, where would you go?",
	"What’s the most underrated food?",
	"What’s your dream breakfast?",
	"If you could collect anything, what would it be?",
	"What's a sport you enjoy watching?",
	"What’s the most photogenic place you’ve been?",
	"If you could change your name, what would you pick?",
	"What’s the cutest animal you’ve seen in person?",
}


func getRandomGetToKnowQuestion() string {
	return getToKnowQuestions[rand.Intn(len(getToKnowQuestions))]
}

func GetToKnowHandler(w http.ResponseWriter, r *http.Request) {
	question := getRandomGetToKnowQuestion()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, `{"handler": "/handlers/text/gettoknow","question": "%s", "status": "success"}`, question)
}
