package wouldyourather_handler

import (
	"fmt"
	"math/rand"
	"net/http"
	"time"
)

func init() {
	rand.Seed(time.Now().UnixNano())
}

var wouldYouRatherQuestions = []string{
	"Would you rather be able to fly or be invisible?",
	"Would you rather live in the mountains or by the beach?",
	"Would you rather have unlimited money or unlimited time?",
	"Would you rather never use social media again or never watch TV again?",
	"Would you rather be famous or be the best friend of someone famous?",
	"Would you rather have the ability to talk to animals or speak all human languages?",
	"Would you rather always be 10 minutes late or always be 20 minutes early?",
	"Would you rather lose all your money or all your photos?",
	"Would you rather have free Wi-Fi wherever you go or free coffee wherever you go?",
	"Would you rather live in the past or the future?",
	"Would you rather be without internet for a week or without your phone?",
	"Would you rather always have to sing instead of speak or always have to dance while walking?",
	"Would you rather never eat your favorite food again or only eat your favorite food?",
	"Would you rather have a pause or a rewind button for your life?",
	"Would you rather be able to read minds or be able to see the future?",
	"Would you rather have unlimited sushi or unlimited tacos?",
	"Would you rather explore space or the deep ocean?",
	"Would you rather be a famous athlete or a famous musician?",
	"Would you rather never have to sleep or never have to eat?",
	"Would you rather always be too hot or always be too cold?",
	"Would you rather have super strength or super intelligence?",
	"Would you rather play video games all day or watch movies all day?",
	"Would you rather be a dragon or own a dragon?",
	"Would you rather have all traffic lights turn green for you or never have to stand in line again?",
	"Would you rather be able to teleport or have a flying car?",
	"Would you rather have the ability to talk to your past self or your future self?",
	"Would you rather win the lottery or live twice as long?",
	"Would you rather be fluent in all languages or be a master of every musical instrument?",
	"Would you rather have the power to freeze time or reverse time?",
	"Would you rather be the funniest person alive or the smartest person alive?",
	"Would you rather have unlimited pizza or unlimited ice cream?",
	"Would you rather live in a fantasy world or a sci-fi world?",
	"Would you rather be the best player in a bad team or the worst player in a good team?",
	"Would you rather lose your keys or your phone?",
	"Would you rather have a personal chef or a personal driver?",
	"Would you rather suddenly be 10 years older or 10 years younger?",
	"Would you rather explore the depths of the ocean or the far reaches of space?",
	"Would you rather have a photographic memory or an IQ of 200?",
	"Would you rather always have to tell the truth or always have to lie?",
	"Would you rather be in a zombie apocalypse or an alien invasion?",
	"Would you rather have the perfect job or the perfect relationship?",
	"Would you rather live in a virtual reality or in the real world with unlimited resources?",
	"Would you rather know how you will die or when you will die?",
	"Would you rather give up all drinks except water or give up eating anything that was cooked?",
	"Would you rather have unlimited battery life on all devices or free Wi-Fi wherever you go?",
	"Would you rather be able to speak to animals or be able to speak any language?",
	"Would you rather have robot servants or robot friends?",
	"Would you rather go back in time and meet your ancestors or go into the future and meet your descendants?",
	"Would you rather fight 100 duck-sized horses or one horse-sized duck?",
	"Would you rather have to read aloud every word you read or sing everything you say?",
	"Would you rather give up social media for a year or give up gaming for a year?",
	"Would you rather have your dream job but live in a place you hate, or have a job you hate but live in your dream location?",
	"Would you rather live without music or live without movies/TV?",
	"Would you rather always be 30 minutes late or always be 2 hours early?",
	"Would you rather be a superhero or a supervillain?",
	"Would you rather be a famous actor or a famous musician?",
	"Would you rather have the ability to control fire or water?",
	"Would you rather never be able to use a touchscreen or never be able to use a keyboard and mouse?",
	"Would you rather swap houses with your worst enemy or swap phones with them?",
	"Would you rather live in a world with no technology or a world with no animals?",
	"Would you rather have the ability to teleport anywhere or the ability to read minds?",
	"Would you rather be a famous YouTuber or a famous Twitch streamer?",
	"Would you rather always have to speak in rhymes or always have to speak in third person?",
	"Would you rather be the best at something that no one takes seriously or be average at something well respected?",
	"Would you rather live in a haunted mansion or in a tiny apartment with annoying neighbors?",
	"Would you rather have all traffic lights turn green for you or never have to wait in line again?",
	"Would you rather have permanent cheeto dust on your fingers or a permanent tiny rock in your shoe?",
	"Would you rather be able to speak to your pet or be able to speak to strangers' pets?",
	"Would you rather have edible slime or drinkable rocks?",
	"Would you rather have to use a flip phone for the rest of your life or never be able to use a smartphone again?",
	"Would you rather have every song turn into a Rickroll or every movie/show turn into The Emoji Movie?",
	"Would you rather play Among Us with your friends in real life or play Minecraft in real life?",
	"Would you rather be able to instantly create perfect memes or always reply with the perfect comeback?",
	"Would you rather have to text everything in emojis or speak everything in hashtags?",
	"Would you rather know all Discord server secrets or know what everyone really thinks about you?",
	"Would you rather have the perfect gaming setup or never experience lag again?",
	"Would you rather join any Discord server in the world or have your own server with 100,000 active members?",
	"Would you rather only be able to communicate through voice channels or only through text channels?",
	"Would you rather have animated Discord avatars or custom Discord sounds?",
	"Would you rather be a mod in your favorite Discord server or be friends with your favorite content creator?",
	"Would you rather have to send a voice message for every text or have to use video calls instead of voice calls?",
	"Would you rather have all your DMs public or have all your browser history public?",
	"Would you rather be famous on TikTok or famous on YouTube?",
	"Would you rather lose access to all streaming services or all gaming platforms?",
	"Would you rather every game you play be pay-to-win or have unskippable 30-second ads every 10 minutes?",
	"Would you rather be stuck in your favorite game or your favorite movie?",
	"Would you rather only be able to play single-player games or only multiplayer games?",
	"Would you rather have Discord nitro forever or free subscriptions to any three streaming services?",
	"Would you rather instantly master any game you play or never have to pay for games again?",
	"Would you rather your mic always be slightly too quiet or slightly too loud?",
	"Would you rather have to use light mode on all apps or have every app randomly switch between light and dark mode?",
	"Would you rather always get matched with toxic teammates or always play against smurfs?",
	"Would you rather be able to see who viewed your profile or see who's talking about you in other servers?",
	"Would you rather have to talk in memes or respond only with GIFs?",
	"Would you rather have the ability to unsend any message ever sent or edit any message you've ever received?",
	"Would you rather be able to ping everyone without restrictions or have everyone always read your messages first?",
	"Would you rather know everyone's online status even when they appear offline or see everyone's deleted messages?",
	"Would you rather have a custom Discord role in every server or a custom emoji that only you can use?",
	"Would you rather build the perfect PC or have every console ever made?",
	"Would you rather have to speak in your highest voice or your lowest voice in voice chats?",
	"Would you rather always be the imposter in Among Us or never be the imposter?",
	"Would you rather have every notification sound be your favorite song or never hear notification sounds again?",
	"Would you rather always appear online or always appear offline?",
	"Would you rather everyone hear every sound in your room during calls or have your camera randomly turn on during calls?",
	"Would you rather know who has blocked you or know who has muted your server?",
	"Would you rather have an AI friend that knows everything about you or a random celebrity join your server once a week?",
	"Would you rather have perfect aim in FPS games or perfect timing in rhythm games?",
	"Would you rather your texts always be read but rarely responded to or rarely read but always responded to?",
	"Would you rather live in a world where everyone uses the same app to communicate or where every person uses a different app?",
	"Would you rather get notified for every single message in all your servers or never get notifications?",
	"Would you rather have unlimited server boosts or unlimited custom emojis?",
	"Would you rather be able to hear what people say about you when you leave a voice channel or see what they type about you in private chats?",
	"Would you rather play with 200ms ping forever or have your game crash once an hour?",
	"Would you rather have to use a controller for PC games or a keyboard/mouse for console games?",
	"Would you rather your voice always echo in calls or your text messages always send twice?",
	"Would you rather get DMed by random people daily or never be able to DM someone first?",
	"Would you rather have to livestream everything you do on your computer or have someone always watching over your shoulder?",
	"Would you rather lose connection during important conversations or have your messages delayed by 5 minutes?",
	"Would you rather always be first to reply in every conversation or always be last?",
	"Would you rather have every message you send be read by all your contacts or have all your gaming achievements public?",
	"Would you rather gain 1000 followers who never interact or 10 followers who always engage with your content?",
	"Would you rather give up voice chat forever or text chat forever?",
	"Would you rather have the ability to turn any conversation into a game or turn any game into a meaningful conversation?",
	"Would you rather only be able to share memes or only be able to share selfies?",
	"Would you rather know everyone's real name online or know everyone's exact age?",
	"Would you rather be able to delete anyone's message or edit anyone's username?",
	"Would you rather have everyone use your favorite emojis or everyone adopt your typing style?",
	"Would you rather have all your online friends live in your city or you be able to teleport to any server meetup?",
	"Would you rather get a notification for everything happening in your servers or miss important announcements?",
	"Would you rather have to use push-to-talk forever or have open mic permanently?",
	"Would you rather have extremely slow typing speed but perfect grammar or lightning fast typing with terrible spelling?",
	"Would you rather lose all your digital friends or one real-life friend?",
}

func getRandomWouldYouRather() string {
	return wouldYouRatherQuestions[rand.Intn(len(wouldYouRatherQuestions))]
}

func WouldYouRatherHandler(w http.ResponseWriter, r *http.Request) {
	question := getRandomWouldYouRather()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, `{"handler": "/handlers/text/wouldyourather","question": "%s", "status": "success"}`, question)
}
